# Generated by Django 4.2.7 on 2024-02-29 20:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_category_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=uuid.UUID('e24d575b-1b43-4f9c-96f1-7197e279a7c1'), unique=True),
        ),
    ]
